# Generated by Django 5.0.6 on 2024-07-03 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utensils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uten_id', models.SmallIntegerField(unique=True)),
                ('uten_name', models.CharField(max_length=100, unique=True)),
                ('uten_location', models.SmallIntegerField(null=True)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchased_date', models.DateField(blank=True, null=True)),
                ('Bill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Rate', models.IntegerField(blank=True, null=True)),
                ('Quantity_purchased', models.IntegerField(blank=True, null=True)),
                ('Balance', models.IntegerField(blank=True, null=True)),
                ('chem_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemicals')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admn_no', models.IntegerField()),
                ('Date', models.DateField(blank=True, null=True)),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(choices=[('chemistry', 'Chemistry'), ('physics', 'Physics'), ('zoology', 'Zoology'), ('botony', 'Botony')], max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], default='Pending', max_length=10)),
                ('Year', models.SmallIntegerField(blank=True, choices=[(1, 'I year'), (2, 'II year'), (3, 'III year')], null=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.utensils')),
            ],
        ),
    ]
