# Generated by Django 5.0.6 on 2024-07-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
