# Generated by Django 5.0.6 on 2024-06-10 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicals',
            name='Issued_to_whom',
        ),
        migrations.RemoveField(
            model_name='chemicals',
            name='Purchased_date',
        ),
        migrations.RemoveField(
            model_name='chemicals',
            name='Quantity_issued',
        ),
        migrations.RemoveField(
            model_name='chemicals',
            name='Quantity_purchased',
        ),
        migrations.RemoveField(
            model_name='chemicals',
            name='Rate',
        ),
        migrations.CreateModel(
            name='PurchasedDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchased_date', models.DateField(blank=True, null=True)),
                ('Rate', models.IntegerField(blank=True, null=True)),
                ('Quantity_purchased', models.IntegerField(blank=True, null=True)),
                ('Quantity_issued', models.IntegerField(blank=True, null=True)),
                ('Issued_to_whom', models.CharField(default='Unknown', max_length=100)),
                ('chem_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemicals')),
            ],
        ),
    ]
