# Generated by Django 5.0.6 on 2024-06-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0002_remove_chemicals_issued_to_whom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.SmallIntegerField(blank=True, null=True, unique=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(choices=[('chemistry', 'Chemistry'), ('physics', 'Physics'), ('zoology', 'Zoology'), ('botony', 'Botony')], max_length=100)),
                ('Year', models.SmallIntegerField(blank=True, choices=[(1, 'I year'), (2, 'II year'), (3, 'III year')], null=True)),
                ('Item', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utensils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uten_id', models.SmallIntegerField(unique=True)),
                ('uten_name', models.CharField(max_length=100, unique=True)),
                ('uten_Location', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='purchaseddetails',
            name='Issued_to_whom',
            field=models.CharField(max_length=100),
        ),
    ]
