# Generated by Django 5.0.6 on 2024-07-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0002_fine_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utensils',
            name='uten_id',
        ),
    ]
