# Generated by Django 5.0.6 on 2024-06-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0003_fine_utensils_alter_purchaseddetails_issued_to_whom'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='ststus',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('recived', 'Recived')], default='pending', max_length=10, null=True),
        ),
    ]
