# Generated by Django 5.0.6 on 2024-07-05 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0003_remove_utensils_uten_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtsensilsStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('utensil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.utensils')),
            ],
        ),
    ]
