# Generated by Django 5.0.6 on 2024-06-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0004_fine_ststus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fine',
            old_name='ststus',
            new_name='status',
        ),
    ]
