# Generated by Django 5.0.6 on 2024-06-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0006_alter_fine_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('recived', 'Recived')], default='Pending', max_length=10),
        ),
    ]
