# Generated by Django 5.0.6 on 2024-06-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0007_alter_fine_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseddetails',
            name='Issued_to_whom',
        ),
    ]
