# Generated by Django 5.0.6 on 2024-06-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0008_remove_purchaseddetails_issued_to_whom'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseddetails',
            name='Bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
