# Generated by Django 5.0.6 on 2024-06-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0011_remove_purchaseddetails_balance_chemicals_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemicals',
            old_name='chem_name',
            new_name='chemical_name',
        ),
        migrations.RenameField(
            model_name='utensils',
            old_name='uten_Location',
            new_name='uten_location',
        ),
        migrations.RemoveField(
            model_name='chemicals',
            name='Balance',
        ),
        migrations.AlterField(
            model_name='fine',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], default='Pending', max_length=10),
        ),
    ]
