# Generated by Django 5.0.6 on 2024-06-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0012_rename_chem_name_chemicals_chemical_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemicals',
            old_name='chemical_name',
            new_name='chem_name',
        ),
        migrations.AddField(
            model_name='chemicals',
            name='Balance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
