# Generated by Django 5.0.6 on 2024-06-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0014_remove_chemicals_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseddetails',
            old_name='Quantity_issued',
            new_name='Balance',
        ),
    ]
