# Generated by Django 5.0.6 on 2024-06-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0015_rename_quantity_issued_purchaseddetails_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemicals',
            old_name='chem_name',
            new_name='chemical_name',
        ),
    ]
