# Generated by Django 5.0.6 on 2024-06-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0016_rename_chem_name_chemicals_chemical_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicals',
            name='chemical_name',
            field=models.CharField(max_length=200),
        ),
    ]
